### ISSUE TITLE
ArrayIndexOutOfBoundsException : null

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Engine-Room/Flywheel#51] opened 2021-12-01 23:33 UTC
I have a player of my pack, [Create on a Potato PC](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato/files/3534557), who is playing on a 3rd party server and she crashes sometimes if she uses /rtp from FTB. It seems flywheel is throwing an error `ArrayIndexOutOfBoundsException : null`

Minecraft: 1.116.5
Forge: 36.2.9

Mod List
 - alexsmobs-1.12.1
 - allomancy-4.3.2
 - angelring-1.16.5-1.3.4.1
 - Apotheosis-1.16.5-4.8.0
 - appleskin-forge-mc1.16.x-2.1.0
 - architectury-1.23.33-forge
 - armorpointspp-1.16.5-2.0.0
 - BiomesOPlenty-1.16.5-13.1.0.482-universal
 - BorderlessWindow-1.16.5-1.2.1
 - Botania-1.16.5-419
 - bwncr-1.16.5-3.10.16
 - charginggadgets-1.3.0
 - citadel-1.8.1-1.16.5
 - cloth-config-4.11.26-forge
 - Clumps-6.0.0.26
 - comforts-forge-1.16.5-4.0.1.3
 - Controlling-7.0.0.28
 - CookingForBlockheads_1.16.5-9.3.4
 - craftingstation-4.1.1
 - CraftingTweaks_1.16.5-12.2.1
 - crashutilities-3.12
 - create-mc1.16.5_v0.3.2f
 - createaddition-1.16.5-20211122b
 - createplus-1.16.4_v0.3.2.1
 - Cucumber-1.16.4-4.1.10
 - curios-forge-1.16.5-4.0.5.3
 - CustomStartingGear-1.16.5-2.0.3-universal
 - DefaultOptions_1.16.5-12.2.1
 - Disenchanting-forge-1.16.5-1.7.2
 - fancymenu_2.3.3_MC_1.16.2-1.16.5
 - FarmingForBlockheads_1.16.5-7.3.1
 - FastLeafDecay-v25
 - FastWorkbench-1.16.4-4.5.1
 - feruchemy-1.2.2
 - flywheel-1.16-0.2.4
 - forbidden_arcanus-16.2.0-beta-4
 - ftb-backups-2.1.1.6
 - ftb-chunks-forge-1605.3.2-build.57
 - ftb-essentials-1605.1.4-build.20
 - ftb-library-forge-1605.3.3-build.74
 - ftb-quests-forge-1605.3.5-build.64
 - ftb-ranks-1605.1.4-build.12-forge
 - ftb-teams-forge-1605.2.2-build.32
 - ftb-ultimine-forge-1605.3.0-build.25
 - gardenofglass-1.7
 - globalxp-1.16.5-v1.8
 - gravestone-1.16.5-1.0.7
 - invtweaks-1.16.4-1.0.1
 - item-filters-forge-1605.2.5-build.9
 - jei-1.16.5-7.7.1.121
 - konkrete_1.3.0_MC_1.16.2-1.16.5
 - kotlin_libraries-1.0-6
 - kubejs-create-1605.1.2-build.7
 - kubejs-forge-1605.3.18-build.141
 - metalbarrels-1.16.2-3.3b
 - moredragoneggs-1.4
 - moreoverlays-1.18.15-mc1.16.5
 - Morpheus-1.16.5-4.2.70
 - MouseTweaks-2.14-mc1.16.2
 - OpenLoader-1.16.5-9.0.3
 - OptiFine_1.16.5_HD_U_G8
 - pamhc2foodcore-1.16.3-1.0.2
 - Patchouli-1.16.4-53.2
 - PickleTweaks-1.16.5-5.2.5
 - Placebo-1.16.5-4.6.0
 - polymorph-forge-1.16.5-0.25
 - reap-1.16.5-1.0.1
 - ReAuth-1.16-Forge-3.9.3
 - refinedstorage-1.9.15
 - refinedstorageaddons-0.7.3
 - repurposed_structures_forge-3.2.5+1.16.5
 - rhino-forge-1605.1.4-build.63
 - rsrequestify-1.16.5-2.1.3
 - ServerTabInfo-1.16.4-1.3.3
 - shutupexperimentalsettings-1.0.3
 - silent-gear-1.16.5-2.6.30
 - silent-lib-1.16.3-4.9.6
 - SilentGems-1.16.3-3.7.16
 - SoL-Carrot-1.16.5-1.10.1
 - sounddeviceoptions-1.4.3
 - StorageDrawers-1.16.3-8.3.0
 - theoneprobe-1.16-3.1.4
 - torchmaster-2.3.8
 - u_team_core-1.16.5-3.2.1.196
 - useful_backpacks-1.16.5-1.12.1.90
 - valhelsia_core-16.0.11
 - WaterStrainer-1.16.3-10.0.0
 - windowlogging-mc1.16.3_v0.0.4
 - Wyrmroost-1.16.3-1.2.11
 - Xaeros_Minimap_21.22.2_Forge_1.16.5
 - XaerosWorldMap_1.18.3_Forge_1.16.5

[crash-2021-12-01_17.57.26-client.txt](https://github.com/Jozufozu/Flywheel/files/7637713/crash-2021-12-01_17.57.26-client.txt)
https://crashy.net/RpgBg7TF4gqL9aJifJQg

**Comment by Jozufozu** [comment] 2021-12-02 21:19
Duplicate of #23, seems like this user is still on Flywheel 0.2.0

**Closed as completed by Jozufozu** 2021-12-02 21:19 UTC
