### ISSUE TITLE
Flywheel 0.5.X causes extra severe artifacts with active windmills when using Optifine shaders.

### ISSUE THREAD

**Issue by antauriprime** [Engine-Room/Flywheel#85] opened 2021-12-30 17:09 UTC
### Describe the Bug

Flywheel 0.4.X used to cause active windmills to produce wanky shadows that would change directions alongside your camera, which was bearable. But 0.5.X brought some seriously unbearable artifacts (new ones move with your camera too).

Setting "backend" option to "OFF" and restarting the game did nothing.
BSL, Complementary and Sildur's Enhanced Default have identical artifacts.

0.4.X used to say "off" or something along those lines in the F3 debug menu even when it was set to "ON" in the config.
0.5.X says "GL33 Instanced Arrays" even though I'm using shaders. (Shouldn't is say "OFF" as well? Mod page says flywheel doesn't work with shaders).

The worst part is, I can't even downgrade to the old mod pair now. Some up to date mods (probably some support lib mods) in my custom modpack are now not comparable with the old versions of Create/Flywheel and figuring out which ones would take me an absolute crapton of time :( 

### Reproduction Steps

1. Create any "Windmill Bearing" based contraption that could be activated
2. Activate said contraption

### Expected Result

Either the lack of artifacts altogether or at the very least some wanky shadows instead of whatever this new stuff is.

### 0.4.X with shaders:
![27NQegJ](https://user-images.githubusercontent.com/30935221/147862113-d267b63d-3816-47f1-830a-04c1e02e7a8a.png)

### 0.5.X with shaders:
![lCfU61y](https://user-images.githubusercontent.com/30935221/147862068-0cf8d1aa-3b1b-435e-94d9-cdea24529ec9.png)
![nDX4h1Y](https://user-images.githubusercontent.com/30935221/147862087-5a61d033-b1e4-40e1-8168-465046151b8d.png)

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce 970

### Mod Version

0.5.0

### Minecraft Version

1.18.1

### Forge Version

39.0.8/39.0.9 both have the problem

### Other Mods

**There is no crash and and the issue occurs even when only the 3 necessary mods are installed, but here's the list, just in case:**

1.18.1-betteramethyst-1.0.jar
AI-Improvements-1.18-0.4.0.jar
alexsmobs-1.15.1.jar
AmbientSounds_v5.0.0_mc1.18.1.jar
Amplified Nether 1.0.1 ~ Forge.jar
appleskin-forge-mc1.18-2.2.0.jar
architectury-3.3.6.jar
AutoRegLib-1.7-52.jar
azalea-FORGE-3.0.0.jar
balm-2.4.0+0.jar
beenfo-1.18.1-forge39.0.9-1.2.jar
BetterAdvancements-1.18.1-0.1.2.122.jar
betterfpsdist-1.18-1.1.jar
BetterThirdPerson-Forge-1.18-1.6.0.jar
BiomesOPlenty-1.18.1-15.0.0.50-universal.jar.disabled
citadel-1.10.8-1.18.jar
cloth-config-6.1.48-forge.jar
Clumps-forge-1.18.1-8.0.4.jar
collective-1.18.1-3.8.jar
configured-1.5.1-1.18.1.jar
Controlling-forge-1.18.1-9.0.7.jar
corail_woodcutter-1.18-2.2.0.jar
corpse-1.18.1-1.0.0.jar
CosmeticArmorReworked-1.18.1-v1.jar
create-mc1.18.1_v0.4b.jar
createchunkloading-0.3.1.jar
CreativeCore_v2.4.1_mc1.18.1.jar
Ding-1.18-1.3.0.jar
durabilitytooltip-1.0.1-mc1.18.jar
EarthMobs-1.18.1-0.5.2.jar
EasyMagic-v3.2.0-1.18.1-Forge.jar
effective_for_forge-1.001.jar
EnchantmentDescriptions-Forge-1.18.1-9.0.5.jar
extremeSoundMuffler-3.19_1.18.jar
FarmersDelight-1.18.1-1.0.0.jar
FastFurnace-1.18.1-6.0.1.jar
FastLeafDecay-27.jar
FastSuite-1.18.1-3.0.0.jar
FastWorkbench-1.18.1-6.0.0.jar
fishingreal-1.18-1.2.jar
fixedanvilrepaircost_1.18.1-1.7.jar
flywheel-forge-1.18-0.5.0a.jar
FpsReducer-forge-1.25-mc1.18.jar
GameMenuModOption-1.18-Forge-1.13.jar
goblintraders-1.7.0-1.18.1.jar
goprone-1.18.1-1.6.0.jar
Iceberg-1.18.1-1.0.31.jar
inventoryessentials-forge-1.18-4.0.0.jar
inventorysorter-1.18-19.0.0.jar
jeed-1.18-1.6.jar
JustEnoughResources-1.18.1-0.13.1.138.jar
kleeslabs-forge-1.18-11.0.0.jar
LegendaryTooltips-1.18.1-1.1.5.jar
light-overlay-6.0.4-forge.jar
mcw-windows-2.0.2-mc1.18.1.jar
MmmMmmMmmMmm-1.18-1.5.0.jar
modnametooltip-1.18.1-1.18.0.jar
mores-1.1.jar
MouseTweaks-forge-mc1.18-2.21.jar
musicdr-1.4.0.jar
mutil-1.18.1-4.0.0.jar
NaturesCompass-1.18.1-1.9.4-forge.jar
netherportalspread_1.18.1-5.7.jar
notenoughcrashes-4.1.3+1.18.1-forge.jar
OptiFine_1.18.1_HD_U_H4.jar
Patchouli-1.18.1-63.jar
physics-mod-2.6.3-mc-1.18-forge.jar
PickUpNotifier-v3.1.0-1.18.1-Forge.jar
Placebo-1.18.1-6.0.3.jar
polymorph-forge-1.18.1-0.33.jar
PuzzlesLib-v3.1.3-1.18.1-Forge.jar
Quark-3.0-334.jar
QuarkOddities-1.18.jar
rhino-forge-1800.1.6-build.81.jar
RoughlyEnoughItems-7.1.357.jar
RoughlyEnoughItems-jei-internals-workaround-7.1.356.jar
seamless_loading_screen-1.18-3.0.0.jar
selene-1.18-1.11.jar
SereneSeasons-1.18.1-6.0.0.8-universal.jar
shutupexperimentalsettings-1.0.4-1.18+.jar
smarterfarmers-1.18-1.2.1.jar
snowundertrees-1.18-1.1.5.jar
SoL-Carrot-1.18.1-1.12.0.jar
soundphysics-forge-1.18.1-1.0.3.jar
starterkit_1.18.1-3.2.jar
StylishEffects-v3.0.2-1.18.1-Forge.jar
supermartijn642configlib-1.0.9-mc1.18.jar
supplementaries-1.18.1-1.1.3.jar
swingthroughgrass-1.18.1-1.8.0.jar
Terralith_v2.0.7_Fabric+Forge.jar
theoneprobe-1.18-5.0.1.jar
TinySkeletons-v3.1.0-1.18.1-Forge.jar
veinmining-forge-1.18.1-0.16.jar
VisualWorkbench-v3.1.0-1.18.1-Forge.jar
waystones-forge-1.18.1-9.0.1.jar
XaerosWorldMap_1.19.0_Forge_1.18.jar
Xaeros_Minimap_21.23.0_Forge_1.18.jar

**Comment by antauriprime** [comment] 2022-01-01 21:22
A bit of an update:

The mod that caused the crash with an older create/flywheel mod pair turned out to be Supplementaries 1.1.3 and older, 'cause starting from 1.1.3 it has support for newer version of Create built in.
So, if you find yourself in a similar situation, downgrading to **Create 0.4a, flywheel 0.4.2 and Supplementaries 1.1.2** could be a decent temporary workaround. Hope somebody will find this info useful.

Btw, Happy New Year, devs!

**Comment by Ameno-Sagiri** [comment] 2022-01-04 13:03
Just wanted to add, this isn't a niche thing. Me and every person playing on my server are all experiencing the same issue, so we had to downgrade flywheel, create, and supplementaries as well. Seems to be triggered by optifine and shaders. Unfortunate.

The thing to take note of here, is flywheel/create updating is the cause of this to break. That means this is not on the Optifine developer to fix. Something that once worked no longer works after you updated, so this problem can't be solely swept under Optifine's rug.

**Comment by apotatomachine** [comment] 2022-01-05 21:27
+1 would also really like to see this bug resolved as it affects my server

**Comment by Jozufozu** [comment] 2022-01-09 23:26
Fixed in latest [Create](https://www.curseforge.com/minecraft/mc-mods/create/files/3600402) and [Flywheel](https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3600401).

**Closed as completed by Jozufozu** 2022-01-09 23:26 UTC
Labels: bug
