### ISSUE TITLE
Crash on Apple M1

### ISSUE THREAD

**Issue by EthanKnop** [Engine-Room/Flywheel#58] opened 2021-12-10 19:56 UTC
Game becomes unresponsive upon joining a new singleplayer world, same issue with or without Create mod included.
[crash-2021-12-10_08.43.50-client.txt](https://github.com/Jozufozu/Flywheel/files/7695146/crash-2021-12-10_08.43.50-client.txt)

**Comment by Jozufozu** [comment] 2021-12-10 22:46
Duplicate of #53

**Closed as completed by Jozufozu** 2021-12-10 22:46 UTC
