### ISSUE TITLE
Crash on Chunk load for 1.18

### ISSUE THREAD

**Issue by Kdenight** [Engine-Room/Flywheel#60] opened 2021-12-10 22:32 UTC
Just loading in new chunks causes me to crash no mods just create and with mods like apple and JEI no texture packs default only and with texture packs Stay True  I've tried using different forge versions  38.0.14 15 16 17 all do this Without Optifine and with Optifine. 

<details> <summary> **_CLICK FOR MORE INFO_** ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/10/21, 2:44 PM
Description: Unexpected error

com.jozufozu.flywheel.backend.gl.error.GlException: mapBufferRange(ARRAY_BUFFER, 0, 1472, 2)
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBufferRange.checkAndMap(MappedBufferRange.java:36) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}</summary>
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBuffer.position(MappedBuffer.java:69) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBufferRange.position(MappedBufferRange.java:25) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.model.ModelPool.uploadPending(ModelPool.java:138) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.model.ModelPool.flush(ModelPool.java:71) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialRenderer.render(InstancedMaterialRenderer.java:32) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialGroup.render(InstancedMaterialGroup.java:52) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.lambda$render$1(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.render(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.renderLayer(InstanceWorld.java:101) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.renderLayer(InstancedRenderDispatcher.java:83) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_12_InstancedRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzf000$renderLayer(LevelRenderer.java:4567) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:1550) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1174) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:830) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.16.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBufferRange.checkAndMap(MappedBufferRange.java:36) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBuffer.position(MappedBuffer.java:69) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.gl.buffer.MappedBufferRange.position(MappedBufferRange.java:25) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.model.ModelPool.uploadPending(ModelPool.java:138) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.model.ModelPool.flush(ModelPool.java:71) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialRenderer.render(InstancedMaterialRenderer.java:32) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterialGroup.render(InstancedMaterialGroup.java:52) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.lambda$render$1(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancingEngine.render(InstancingEngine.java:100) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstanceWorld.renderLayer(InstanceWorld.java:101) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:classloading}
	at com.jozufozu.flywheel.backend.instancing.InstancedRenderDispatcher.renderLayer(InstancedRenderDispatcher.java:83) ~[flywheel-forge-1.18-0.4.0.jar%2354!:1.18-0.4.0] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_12_InstancedRenderDispatcher_renderLayer_RenderLayerEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzf000$renderLayer(LevelRenderer.java:4567) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:1550) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1174) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1050) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Kdenight'/175, l='ClientLevel', x=120.62, y=67.00, z=-46.84]]
	Chunk stats: 961, 549
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,73,-48), Section: (at 0,9,0 in 7,4,-3; chunk contains blocks 112,-64,-48 to 127,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1232 game time, 1232 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18-20211130.085255-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.16.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1538360520 bytes (1467 MiB) / 4672454656 bytes (4456 MiB) up to 6375342080 bytes (6080 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2503
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30069.79
	Virtual memory used (MB): 26143.72
	Swap memory total (MB): 13762.23
	Swap memory used (MB): 2038.62
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6080m -Xms256m -XX:+IgnoreUnrecognizedVMOptions
	Launched Version: forge-38.0.16
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPushMatrix is deprecated and not available in preview contexts.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glOrtho is deprecated and not available in preview contexts.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.' x 1
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.' x 17
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPopMatrix is deprecated and not available in preview contexts.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPopAttrib is deprecated and not available in preview contexts.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Kdenight'/175, l='ServerLevel[Kdenights Create World]', x=120.62, y=67.00, z=-46.84]]
	Data Packs: vanilla, mod:forge, mod:flywheel (incompatible), mod:create, mod:appleskin (incompatible), mod:jei (incompatible)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18-20211130.085255-srg.jar               |Minecraft                     |minecraft                     |1.18                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18-38.0.16-universal.jar                  |Forge                         |forge                         |38.0.16             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		flywheel-forge-1.18-0.4.0.jar                     |Flywheel                      |flywheel                      |1.18-0.4.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18_v0.4.jar                            |Create                        |create                        |0.4                 |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.2.0.jar                  |AppleSkin                     |appleskin                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18-9.0.0.40.jar                             |Just Enough Items             |jei                           |9.0.0.40            |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 5fe91c11-ef8f-4317-b69f-ff9fd8972bd5
	FML: 38.0
	Forge: net.minecraftforge:38.0.16</details>
I put in the crash report in for the fresh install of both Minecraft and forge just flywheel here [crash-2021-12-10_15.25.58-client.txt](https://github.com/Jozufozu/Flywheel/files/7695760/crash-2021-12-10_15.25.58-client.txt)  This is all thru CurseForge if that helps any

**Comment by Jozufozu** [comment] 2021-12-10 22:47
Duplicate of #56, thanks for the full crash report!

**Closed as completed by Jozufozu** 2021-12-10 22:47 UTC

**Comment by Kdenight** [comment] 2021-12-10 22:51
Thanks for the help and info hope this help a little
