### ISSUE TITLE
Flywheel Crashes on Windows 11 with AMD Graphics card

### ISSUE THREAD

**Issue by killalogan101** [Engine-Room/Flywheel#166] opened 2022-12-20 17:36 UTC
### Describe the Bug

I spent multiple hours testing a mod pack and found that the flywheel mod for 1.18.2 will always crash my (fully up-to-date) AMD Card, but will not crash my Laptop running an NVIDIA card. Both computers are running intel processors and windows 11.

### Reproduction Steps

1. Use PC with AMD graphics card and Windows 11 OS
2. Boot up a modpack that includes Flywheel (either by itself or with others)
3. Join multiplayer or single player
4. Game Closes on it's own giving random error codes including (1 and -1073740940)
...

### Expected Result

Expected to run without crashing

### Operating System

windows 11

### What is your GPU?

AMD Radeon RX 6600 XT

### Mod Version

0.6.8

### Minecraft Version

1.18.2

### Loader Version

Forge - 40.1.86

### Other Mods

None

### Additional Context

Works with NVIDIA but not AMD graphics

**Comment by TheLethalMenace** [comment] 2022-12-21 17:56
A buddy of mine and myself are having the same issue on the same version of minecraft, forge version 40.1.80. We both are running windows 10 and both of us have a 5700xt. Same codes and everything. We try to walk around or do anything for less than 15 to 30 seconds and the game crashes. Any advice or troubleshooting would help immensely as I am running out of ideas.

**Comment by killalogan101** [comment] 2022-12-21 18:02
In one of the previous errors I think #164 they recommend using this command in game " /flywheel backend off ". This works (if you can get in for long enough to paste it in) I dont know if you have to do it in the server or if you can also put it in somewhere else.

**Comment by TheLethalMenace** [comment] 2022-12-21 18:44
This seems to have fixed the issue for me at least! Thank you, I will make sure to spread this around. Not sure if it will work for you or not since you're on W11 and I'm on W10 (not too much of a difference). If I have any similar issues with it I will come back to this thread.

**Comment by ArcaneSan** [comment] 2022-12-23 20:44
It appears that the "instancing" setting for flywheel crashes, while off and batching still work

**Comment by bettest** [comment] 2022-12-27 13:22
> In one of the previous errors I think #164 they recommend using this command in game " /flywheel backend off ". This works (if you can get in for long enough to paste it in) I dont know if you have to do it in the server or if you can also put it in somewhere else.

thanks, it works

**Comment by TheUnknownCod3r** [comment] 2022-12-27 17:39
Friend had this issue on our Skyblock world (All The Mods 7: TTS 1.1.9), setting to Batching or off fixed.

**Comment by QuatschVirus** [comment] 2022-12-31 13:15
I have the same issue: World more or less instantly crashing as soon as i start it with flywheel. 

> In one of the previous errors I think #164 they recommend using this command in game " /flywheel backend off ". This works (if you can get in for long enough to paste it in) I don't know if you have to do it in the server or if you can also put it in somewhere else.

You can change the backend in the `flywheel-client.toml` file in your `config` folder. You can also set it to `BATCHING`, which (so far) seemed to also work for me.

**Comment by PepperCode1** [comment] 2022-12-31 22:55
Duplicate of #164.

**Closed as completed by PepperCode1** 2022-12-31 22:55 UTC
Labels: bug

**Comment by webmilio** [comment] 2023-01-05 18:41
It might be a duplicate, but I think it'd be worth it to note this down somewhere in some FAQ. It took me quite a while to find out it was Flywheel.
