### ISSUE TITLE
Incompatible with JourneyMap

### ISSUE THREAD

**Issue by StarskyXIII** [Engine-Room/Flywheel#54] opened 2021-12-10 08:42 UTC
Forge Version: 38.0.16
Flywheel Version: 0.4.0
JourneyMap Version: 5.8.0 alpha 9

When I disabled Flywheel Renderer and remaped by delete map:
![image](https://user-images.githubusercontent.com/71606873/145543410-632ef17a-82ba-4b80-867b-2f7507aa930c.png)

When I Enabled Flywheel Renderer and remaped by delete map:
![image](https://user-images.githubusercontent.com/71606873/145543616-c399c27f-b77e-4bbe-9e39-9fa559415605.png)

Mod List:
![image](https://user-images.githubusercontent.com/71606873/145543911-6040a4f4-bd05-4057-ae73-13e1c47b2afd.png)

**Comment by mysticdrew** [comment] 2021-12-11 20:43
I am the Journeymap dev, 
I noticed some weird issues with flywheel when doing some testing. I have not done much for debugging the issue yet. 
We read chunks from disk for automapping them, I get a lot of these errors. 
`Chunk file at [-136, 65] is in the wrong location; relocating. (Expected [-136, 65], got [0, 0])`
This error comes from 
net.minecraft.world.level.chunk.storage.ChunkSerializer#read  line#72. 

When I get time and get flywheel loaded up indev I will add more details.

**Comment by Jozufozu** [comment] 2021-12-12 00:35
I can't seem to reproduce this, even outside of dev

**Comment by pascalklassen** [comment] 2021-12-16 10:35
I do have the exact same Issue. I am running a Forge `1.18.1 - 39.0.5` Server with Flywheel + Create + Journeymap(`5.8.0alpha9`) and the exact same problems arise to me and my friends playing on the Server. I can even reproduce this by loading up a single player world. Same Issue

**Comment by mysticdrew** [comment] 2021-12-16 13:45
With just create and Journeymap, there seems to be an issue with the Flywheel renderer when we use texSubImage2D. 

GL Error in method: texSubImage2D ERROR: 1282 (SUPPRESSED)
`OpenGL Error in texSubImage2D target:3553, level:0, xoffset:192, yoffset:128, width:16, height:16, format:32993, type:33639, IntBuffer`

**Comment by mysticdrew** [comment] 2021-12-16 14:02
Though, now that I added optifine the big black squares no longer happen.

**Comment by mysticdrew** [comment] 2021-12-19 21:45
Fixed in journeymap 5.8.0 beta4, should be on curseforge shortly.

**Closed as completed** 2021-12-29 18:57 UTC
