### ISSUE TITLE
AMD Graphics Cardrendering error while fly wheel is set to instancing

### ISSUE THREAD

**Issue by Mastermarksmen31** [Engine-Room/Flywheel#223] opened 2024-02-04 17:32 UTC
### Describe the Bug

While using an AMD graphics card while fly is set to instancing, graphical issues with chests, shulker boxes and belts are the only ones I've seen but I'm sure more exist, when the chests and shulkers are placed down, parts of them will appear blacked out randomly.

### Reproduction Steps

1. Launch minecraft with create on a machine using an AMD Graphics card
2. Place a bunch of chests or shulker boxes
3.
...

### Expected Result

Parts of these blocks should appear blacked out

### Screenshots and Videos

![2024-01-30_10 05 44](https://github.com/Jozufozu/Flywheel/assets/53454538/c41baa83-b0f5-4b5a-bc5d-36027af20144)

### Operating System

Windows 11

### What is your GPU?

AMD Radeon RX 6800 XT

### Mod Version

0.5.1

### Minecraft Version

1.18.2

### Loader Version

40.2.10

### Other Mods

Quark chests are seen on the screenshot but this was tested with only create as well and the issue persisted

### Additional Context

I was told to report a bug here as well after leaving one on the Create GitHub, the issue seems to fix itself when switching to flywheel batching using "/flywheel backend batching"

**Comment by mindbound** [comment] 2024-02-09 13:23
I'm also having this exact same problem, also on Windows 11, using AMD Radeon RX 7600 XT.

Setting the backend to batching does work.

**Comment by Jozufozu** [comment] 2024-02-16 22:13
Please make sure you are using the latest [adrenalin drivers](https://www.amd.com/en/support) for your GPU (should see a download for "AMD Software: Adrenalin Edition").
Older AMD drivers have *issues*

**Comment by mindbound** [comment] 2024-02-17 01:23
I am using the latest stable, 24.1.1.

**Comment by awbuckst11181999** [comment] 2024-02-19 19:22
I updated my drivers and ran into this issue in 1.20.1. /flywheel batching seems to have solved it, but does effect framerate so a fix would be great

**Comment by Marco6789** [comment] 2024-02-20 12:47
I would like to add to this that i do not believe this is an AMD specific issue. [this] (https://github.com/Jozufozu/Flywheel/issues/226) issue has been opened by another user describing the same problem using an Nvidia GPU. I have also left a comment there that goes into detail on how to fix it.

**Comment by Jozufozu** [comment] 2024-02-21 17:08
I'm able to reproduce this on an intel iGPU. Resolving as duplicate of #226

**Closed as completed by Jozufozu** 2024-02-21 17:08 UTC
Labels: bug
