### ISSUE TITLE
[MacOS] Game crashes while trying to load world

### ISSUE THREAD

**Issue by Grzegorz1337** [Engine-Room/Flywheel#63] opened 2021-12-11 17:20 UTC
Mods:
Forge - 39.0.0
Flywheel 1.18-0.4.0
Create - 1.18 - v0.4
Xaeros minimap - 21.22.3.1
Jej - 9.0.0.40

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit code: 255

[crash-2021-12-11_17.26.40-client.txt](https://github.com/Jozufozu/Flywheel/files/7697358/crash-2021-12-11_17.26.40-client.txt)

Crash takes place during exploration (move few blocks to any direction, or sometimes even if standing still after few seconds) so I assume this may be a chunk loading problem.

**Comment by ConnerEnders** [comment] 2021-12-11 17:41
Same issue here

**Comment by Jozufozu** [comment] 2021-12-11 18:38
Duplicate of #53, thanks for the crash log!

**Closed as completed** 2021-12-11 18:39 UTC
