### ISSUE TITLE
Flywheel Crash about Hopper

### ISSUE THREAD

**Issue by SHXRKIEgg** [Engine-Room/Flywheel#129] opened 2022-05-07 04:20 UTC
### Describe the Bug

I am trying to make a compact chicken cooker. I crafted a hopper minecart and placed it on top of a rail that was sitting on top of a regular hopper. When I placed the hopper minecart on the rail my game crashed and now I can't open the world without it crashing.

### Reproduction Steps

1. Place hopper facing into chest
2. Place rail on hopper
3. Place hopper minecart on rail.

### Expected Result

Not Crash

### Crash Report or Log

https://pastebin.com/ZQTSaJRY

### Operating System

Windows 10

### What is your GPU?

RTX 2808 Super

### Mod Version

0.6.2

### Minecraft Version

1.18.1

### Loader Version

FORGE 40.1.2

### Other Mods

**Using the Better Minecraft PLUS 1.18.2 Modpack** 
[Tool Belt (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/tool-belt)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Additional Banners (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/additional-banners)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[RevampedWolf (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/revampedwolf)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[Config Menus for Forge (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/config-menus-forge)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Motschen's Better Leaves (by Motschen)](https://www.curseforge.com/minecraft/texture-packs/motschens-better-leaves)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Client Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/client-tweaks)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Stalwart Dungeons (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons)
[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[Inventory HUD+ (by dmitrylovin)](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge)
[Simple Shops (by wolforce)](https://www.curseforge.com/minecraft/mc-mods/simple-shops)
[Nourished Nether (by MuffinsDev)](https://www.curseforge.com/minecraft/mc-mods/nourished-nether)
[Chipped (by ToadstoolStudios)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Snuffles (by schnappdragon)](https://www.curseforge.com/minecraft/mc-mods/snuffles)
[Additional Bars - Biomes O' Plenty addon (by Gamma1772)](https://www.curseforge.com/minecraft/mc-mods/additional-bars-biomes-o-plenty-addon)
[JEITweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/jeitweaker)
[FTB Quests (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Enlightened End (by MuffinsDev)](https://www.curseforge.com/minecraft/mc-mods/enlightened-end)
[Curious Lights (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curious-lights)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[JustTimm's Vanilla Additions Dark GUI Add-On (by justtimmnl)](https://www.curseforge.com/minecraft/texture-packs/justtimms-vanilla-additions-dark-gui-add-on)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Blue Skies (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/blue-skies)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Village Artifacts (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/villager-tools)
[More Villagers (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/more-villagers)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Drippy Loading Screen [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screen)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Upgraded Netherite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[FancyMenu [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/fancymenu-forge)
[Pigsteel [Forge] (by uraneptus)](https://www.curseforge.com/minecraft/mc-mods/pigsteel-forge)
[Improved Mount HUD [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/improved-mount-hud-forge)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[Enchant With Mob (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/enchant-with-mob)
[BisectHosting Server Integration Menu [FORGE] (by BisectHosting)](https://www.curseforge.com/minecraft/mc-mods/bisecthosting-server-integration-menu-forge)
[Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[The Conjurer (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/the-conjurer)
[Wandering Trapper (by lilypuree)](https://www.curseforge.com/minecraft/mc-mods/wandering-trapper)
[Item Filters (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/item-filters)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
['Dustrial Decor (by BlueDuckYT)](https://www.curseforge.com/minecraft/mc-mods/dustrial-decor)
[Jade Addons (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
[Biome Makeover (Forge) (by Lemonszz)](https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge)
[Create Plus (by Robocraft999)](https://www.curseforge.com/minecraft/mc-mods/create-plus)
[Delete Worlds To Trash [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/delete-worlds-to-trash-forge)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[Entity Culling Fabric/Forge (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Decorative Blocks Compat (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks-compat)
[Scuba Gear (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/scuba-gear)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Xaero's Minimap - Modded Support (by babybluetit)](https://www.curseforge.com/minecraft/texture-packs/xaeros-minimap-modded-support)
[Radium Reforged (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radium-reforged)
[Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Not Enough Animations (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Akashic Tome (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/akashic-tome)
[Upgraded Core (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-core)
[Earth Mobs (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/earth-mobs)
[Radon (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radon)
[Magnesium/Rubidium Extras (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Simple Storage Network (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Mushlings! (by Wabbajakke28)](https://www.curseforge.com/minecraft/mc-mods/mushlings)
[Additional Additions | Forge (by dqu1jjj)](https://www.curseforge.com/minecraft/mc-mods/additional-additions-forge)
[Immersive Weathering [FORGE] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge)
[Forgotten Recipes - Sculk Sensor, Bundle, Leather and Powder Snow Recipe (by Affehund)](https://www.curseforge.com/minecraft/mc-mods/forgottenrecipes)
[Slimy Stuff (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/slimy-stuff)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[In Control! (by McJty)](https://www.curseforge.com/minecraft/mc-mods/in-control)
[Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Curious Elytra (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curious-elytra)
[Create Cafe (by 1mphuls3)](https://www.curseforge.com/minecraft/mc-mods/create-cafe)
[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[Easy Magic [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Hunter illager (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/hunterillager)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Upgraded Netherite : Items (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-items)
[Upgraded Netherite : Ultimerite (by Rolfmao25)](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-ultimerite)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Additional Structures (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures)
[Snow Pig [Forge] (by uraneptus)](https://www.curseforge.com/minecraft/mc-mods/snow-pig)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Creatures From The Lush Caves! [Forge] (by YeoXuHang)](https://www.curseforge.com/minecraft/mc-mods/creatures-from-the-lush-cave-forge)
[Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[Stay True (by haimcyfly)](https://www.curseforge.com/minecraft/texture-packs/stay-true)
[Corail Woodcutter Extension (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter-extension)
[Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[More Storage Drawers (by RydelFox)](https://www.curseforge.com/minecraft/mc-mods/more-storage-drawers)
[Iron Chests: Restocked (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/ironchests)
[The Graveyard (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[More Axolotl Variants Mod (by Akashii_Kun_)](https://www.curseforge.com/minecraft/mc-mods/mavm)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Void Totem (Forge) (by Affehund)](https://www.curseforge.com/minecraft/mc-mods/voidtotem)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Better-Shields (by ToMe250)](https://www.curseforge.com/minecraft/mc-mods/better-shields)
[Puzzles Lib [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
[Warden & Sculk (by vicalisito)](https://www.curseforge.com/minecraft/mc-mods/sculk-warden)
[Sprout (by ToadstoolStudios)](https://www.curseforge.com/minecraft/mc-mods/sprout)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Trading Post [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/trading-post)
[Compat Makeover (by phoenixknight___)](https://www.curseforge.com/minecraft/mc-mods/compat-makeover)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Selene Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[JEI Enchantment Info (by Phylogeny)](https://www.curseforge.com/minecraft/mc-mods/jei-enchantment-info)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Villager Names (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Pick Up Notifier [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[Iceberg (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Feature NBT Deadlock Be Gone (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone)
[Drawers Tooltip (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/drawers-tooltip)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Blocks + (by shadow_x_666)](https://www.curseforge.com/minecraft/mc-mods/shadow-x-blocks-plus)
[Paintings ++ (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/paintings)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Dynamic Asset Generator (by lukebemish)](https://www.curseforge.com/minecraft/mc-mods/dynamic-asset-generator)
[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[More Babies (Forge & Fabric) (by mammut53m)](https://www.curseforge.com/minecraft/mc-mods/more-babies)
[This Rocks! (Forge) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/this-rocks-forge)
[More Minecarts and Rails (by goldey3)](https://www.curseforge.com/minecraft/mc-mods/more-minecarts)
[XP Tome (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/xp-tome)
[Simple Discord RPC [Forge/Fabric] (by hypherionsa)](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc)
[Curio of Undying (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curio-of-undying)
[FTB Ultimine (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[Duckling (by ToadstoolStudios)](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Paxi (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/paxi)
[Farmer's Respite (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite)
[Overweight Farming (by agentmhkskg)](https://www.curseforge.com/minecraft/mc-mods/overweight-farming)
[Collective (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Structures' Compass (by Samarium_150)](https://www.curseforge.com/minecraft/mc-mods/structures-compass)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Repurposed Structures (Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Volcanic Caverns (by f1ashfyre)](https://www.curseforge.com/minecraft/mc-mods/volcanic-caverns)
[The Gold Rush (by Ddx11__)](https://www.curseforge.com/minecraft/mc-mods/the-gold-rush)
[Architectury API (Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-forge)
[Verdure (by Drigonis_)](https://www.curseforge.com/minecraft/mc-mods/verdure)
[Aquaculture 2 (by Shadowclaimer)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Chimes (by BlewberryPie)](https://www.curseforge.com/minecraft/mc-mods/chimes)
[Village Employment (by EnderPreston)](https://www.curseforge.com/minecraft/mc-mods/village-employment)
[Dark Paintings (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
[Magnum Torch [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[Skinned Lanterns (Forge) (by nuxthefox)](https://www.curseforge.com/minecraft/mc-mods/skinned-lanterns)
[Steve's Vanilla (by is_ktoto)](https://www.curseforge.com/minecraft/mc-mods/steves-vanilla)
[Bygone Nether (by izofar)](https://www.curseforge.com/minecraft/mc-mods/bygone-nether)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[FTB Essentials (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge)
[Easy Shulker Boxes [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-shulker-boxes-forge)
[Starter Kit (Forge) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
[Universal Bone Meal [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/universal-bone-meal-forge)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[Illager Plushies (by kleiders3010)](https://www.curseforge.com/minecraft/mc-mods/illager-plushies)
[Absent by Design (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/absent-by-design)
[Illagers Wear Armor (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Snowy Spirit (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/snowy-spirit)
[Mob Compackability (Mob Compack) (by BottomTextCf28)](https://www.curseforge.com/minecraft/mc-mods/mob-compack)
[The Lost Cities (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities)
[JER Integration (by AlasDiablo)](https://www.curseforge.com/minecraft/mc-mods/jer-integration)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Brixpansion (by EnderPreston)](https://www.curseforge.com/minecraft/mc-mods/brixpansion)
[Better Mods Button [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/better-mods-button)
[Skin Layers 3D (Fabric/Forge) (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Immersive Armors (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[🪵 Twigs (by ninnih_)](https://www.curseforge.com/minecraft/mc-mods/twigs)
[Snow Under Trees (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/snow-under-trees)
[CreateTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/createtweaker)
[Visual Workbench [Forge] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Chisels & Bits - For Forge (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
[Create Stuff Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
[Neko's Enchanted Books (by Nekomaster1000)](https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Equipment Compare (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/equipment-compare)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Additional Bars [FORGE] (by Gamma1772)](https://www.curseforge.com/minecraft/mc-mods/additional-bars)
[Excavated Variants (by lukebemish)](https://www.curseforge.com/minecraft/mc-mods/excavated-variants)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Comforts (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Magnesium/Rubidium Dynamic Lights (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[BiomeInfo (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/biomeinfo)
[Cherished Worlds (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/cherished-worlds)
[Item Highlighter (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-highlighter)
[Integrated Dungeons and Structures (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/idas)
[Runelic (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/runelic)
[Enigmatic Legacy (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Bamboo Everything (Forge) (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/bamboo-everything-forge)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Friends&Foes (Forge) (by faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-forge)

**Comment by ImHoppy** [comment] 2022-06-18 08:11
Hi,
Sorry for your world, I can't reproduce the crash on my side without more information.

The crash log also refers to a "sereneseasons" mod, this may be an incompatibility.
The mod may be trying to change the colors of the entity which Flywheel does not understand?

**Comment by Jozufozu** [comment] 2022-08-19 20:07
This looks like an incompatibility with a shaderpack you may be using. Should be fixed in the latest version of flywheel.

**Closed as completed by Jozufozu** 2022-08-19 20:07 UTC
Labels: bug
