### ISSUE TITLE
where's 1.20?

### ISSUE THREAD

**Issue by LazrProductions** [Engine-Room/Flywheel#187] opened 2023-06-20 03:50 UTC
### Describe the Bug

1.20 wya?

### Reproduction Steps

n/a

### Expected Result

1.20 should be out :)

### Operating System

Window 10

### What is your GPU?

Which ever GPU gets me 1.20

### Mod Version

0.6.8.a

### Minecraft Version

1.19.2

### Loader Version

Forge 46.0.14

**Comment by PepperCode1** [comment] 2023-06-20 04:05
Duplicate of #185.

**Closed as completed by PepperCode1** 2023-06-20 04:05 UTC
Labels: bug
