### ISSUE TITLE
Weird crash on Forge 43.2.0 Minecraft 1.19.2

### ISSUE THREAD

**Issue by shizotoaster** [Engine-Room/Flywheel#165] opened 2022-12-18 16:52 UTC
### Describe the Bug

Game closing 

### Reproduction Steps

1. Install Flywheel
2. Launch the game
3. Enter the world
4. Boom! Access violation JDK crash or game crash without any errors and random exitcode

### Expected Result

Just work normally?

### Screenshots and Videos

![изображение](https://user-images.githubusercontent.com/51480483/208309442-21773750-6add-43b5-a201-9106074b7341.png)

### Crash Report or Log

https://hastebin.com/peyihisara.yaml

### Operating System

Windows 10 

### What is your GPU?

AMD RX 570 4G

### Mod Version

0.6.8

### Minecraft Version

1.19.2

### Loader Version

Forge 43.2.0

### Other Mods

None. Just Forge and Flywheel

### Additional Context

May crash only on specific seeds. For example, on `-1434504688646649113` crashing immidiately when on differrent seed it takes up to several minutes

**Comment by shizotoaster** [comment] 2022-12-18 17:23
Update

Seem to crash only with `instancing` backend

**Comment by MeloTheRogue** [comment] 2022-12-18 20:00
this is the same issue as https://github.com/Jozufozu/Flywheel/issues/164

its because you're using an AMD GPU, try running `/flywheel backend off`

**Comment by Arhzn** [comment] 2022-12-19 09:06
I have the exact SAME GPU (yes with the same amount of VRAM), The way to fix this is to run /flywheel backend off (ingame with commands).

**Comment by shizotoaster** [comment] 2022-12-19 11:58
> try running `/flywheel backend off`

Yeah, I switched to `batching` backend and that helped
Still an issue though

**Comment by humroben** [comment] 2022-12-19 14:20
You can also set the backend type in the config for the mod. I've suggests friends set it to `OFF` instead of `batching`

Also just adding my own confirmation, this only affects Windows systems with AMD cards, not Linux systems, unsure about MAC systems.

**Comment by PepperCode1** [comment] 2022-12-31 22:55
Duplicate of #164.

**Closed as completed by PepperCode1** 2022-12-31 22:55 UTC
Labels: bug

**Comment by jaydenhwang106-ship-it** [comment] 2026-05-24 00:36
flywheel backend off works really well on my potato mac with 50ish fps and the only problem is when you rejoin...

**Comment by jaydenhwang106-ship-it** [comment] 2026-05-24 00:37
To be more specific, flywheel turns back on and makes the world freeze while loading.

**Comment by jaydenhwang106-ship-it** [comment] 2026-05-24 00:37
Automatically*

**Comment by shizotoaster** [comment] 2026-05-24 08:50
> flywheel backend off works really well on my potato mac with 50ish fps and the only problem is when you rejoin...

You shouldn't turn flywheel off unless some very specific problem occurs. Modern flywheel and create versions work just fine on both intel and apple silicon macs. Can confirm flywheel working on m4 mac and on vega56 hackintosh
